// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5HnmNf5jzBT1L4MgAfjO6nSoQQ2CGHhg',
    appId: '1:421892564395:web:3e5bfc26b0a326c8165eee',
    messagingSenderId: '421892564395',
    projectId: 'banas-ai',
    authDomain: 'banas-ai.firebaseapp.com',
    storageBucket: 'banas-ai.firebasestorage.app',
    measurementId: 'G-DF24N21TX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIWgj76z3ujQVU7qQBIX-nUAfeG6ZWOgM',
    appId: '1:421892564395:android:11665e6129655d3c165eee',
    messagingSenderId: '421892564395',
    projectId: 'banas-ai',
    storageBucket: 'banas-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQ3mW8y_TKrmiN_TO3nWnI247cg0TsBY8',
    appId: '1:421892564395:ios:2d0d6db3d9aadcec165eee',
    messagingSenderId: '421892564395',
    projectId: 'banas-ai',
    storageBucket: 'banas-ai.firebasestorage.app',
    iosClientId: '421892564395-pkq1eshpodfr48ihs7vhara55p58e7nr.apps.googleusercontent.com',
    iosBundleId: 'com.example.soilTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQ3mW8y_TKrmiN_TO3nWnI247cg0TsBY8',
    appId: '1:421892564395:ios:2d0d6db3d9aadcec165eee',
    messagingSenderId: '421892564395',
    projectId: 'banas-ai',
    storageBucket: 'banas-ai.firebasestorage.app',
    iosClientId: '421892564395-pkq1eshpodfr48ihs7vhara55p58e7nr.apps.googleusercontent.com',
    iosBundleId: 'com.example.soilTest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5HnmNf5jzBT1L4MgAfjO6nSoQQ2CGHhg',
    appId: '1:421892564395:web:2e34105e9fbbd832165eee',
    messagingSenderId: '421892564395',
    projectId: 'banas-ai',
    authDomain: 'banas-ai.firebaseapp.com',
    storageBucket: 'banas-ai.firebasestorage.app',
    measurementId: 'G-79CWY5C87N',
  );
}
